### ISSUE TITLE
Emulator crash

### ISSUE THREAD

**Issue by mihalycsaba** [join-the-flock/nest#14]
It's the same app I had issues with in https://github.com/join-the-flock/nest/issues/12

Now the app builds successfully. But it turns off my monitor and crashes the emulator.  This has never happened before. I'm using linux, I think it crashed the graphic driver somehow.  I get these exceptions in flutter too, but it never crashed, they're caused by images that are not there. It wasn't an issue with flutter, it didn't crash the app or paused it.

It still runs without issues with flutter.

```
fvm flutter run
Can't load Kernel binary: Invalid kernel binary format version.
FINE: Pub 3.7.0-91.0.dev
FINE: Package Config up to date.
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...                             21.4s
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Installing build/app/outputs/flutter-apk/app-debug.apk...          859ms
I/flutter ( 4631): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
I/flutter ( 4631): dynamic_color: Core palette detected.
Syncing files to device sdk gphone64 x86 64...                     120ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on sdk gphone64 x86 64 is available at: http://127.0.0.1:46473/mVReFwsWf70=/
The Flutter DevTools debugger and profiler on sdk gphone64 x86 64 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:46473/mVReFwsWf70=/
E/FlutterJNI( 4631): Failed to decode image
E/FlutterJNI( 4631): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder.-$$Nest$smnCreate(Unknown Source:0)
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:254)
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1981)
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1973)
E/FlutterJNI( 4631):    at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:561)
D/ProfileInstaller( 4631): Installing profile for com.example.xx
E/FlutterJNI( 4631): Failed to decode image
E/FlutterJNI( 4631): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder.-$$Nest$smnCreate(Unknown Source:0)
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:254)
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1981)
E/FlutterJNI( 4631):    at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1973)
E/FlutterJNI( 4631):    at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:561)

══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack:
#0      _futurize (dart:ui/painting.dart:7332:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:7138:12)
#2      instantiateImageCodecWithSize (dart:ui/painting.dart:2478:60)
#3      PaintingBinding.instantiateImageCodecWithSize (package:flutter/src/painting/binding.dart:147:15)
#4      ImageLoader.loadImageAsync.<anonymous closure> (package:cached_network_image/src/image_provider/_image_loader.dart:65:22)
<asynchronous suspension>
#5      ImageLoader._load (package:cached_network_image/src/image_provider/_image_loader.dart:124:27)
<asynchronous suspension>
#6      new MultiImageStreamCompleter.<anonymous closure> (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:26:7)
<asynchronous suspension>

Image provider:
  CachedNetworkImageProvider("https://steamcdn-a.akamaihd.net/steam/apps/1316760/capsule_184x69.jpg",
  scale: 1.0)
Image key:
  CachedNetworkImageProvider("https://steamcdn-a.akamaihd.net/steam/apps/1316760/capsule_184x69.jpg",
  scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

E/androidemu( 4631): Logging hang event. Number of tasks already hung: 0
E/androidemu( 4631): Metadata:
E/androidemu( 4631):     file: device/generic/goldfish-opengl/system/vulkan_enc/VkEncoder.cpp
E/androidemu( 4631):     function: vkCreateFence
E/androidemu( 4631):     line: 4294
E/androidemu( 4631):     msg: vkCreateFence in VkEncoder
E/androidemu( 4631):     thread: 4717 (0x0000126d)
E/androidemu( 4631):     process name: com.example.xx
E/androidemu( 4631):     Additional information:
E/androidemu( 4631):             seqno: 4309
E/androidemu( 4631):             packetSize: 48
E/androidemu( 4631):             packetContents:  43 4E 00 00 30 00 00 00 D5 10 00 00 2E 00 00 00 05 00 03 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
E/androidemu( 4631): Logging hang event. Number of tasks already hung: 1
E/androidemu( 4631): Metadata:
E/androidemu( 4631):     file: device/generic/goldfish-opengl/system/vulkan_enc/VkEncoder.cpp
E/androidemu( 4631):     function: vkGetFenceStatus
E/androidemu( 4631):     line: 4655
E/androidemu( 4631):     msg: vkGetFenceStatus in VkEncoder
E/androidemu( 4631):     thread: 4731 (0x0000127b)
E/androidemu( 4631):     process name: com.example.xx
E/androidemu( 4631):     Additional information:
E/androidemu( 4631):             seqno: 4310
E/androidemu( 4631):             packetSize: 28
E/androidemu( 4631):             packetContents:  46 4E 00 00 1C 00 00 00 D6 10 00 00 2E 00 00 00 05 00 03 00 7F 08 00 00 17 00 16 00
E/androidemu( 4631): HealthMonitor: Number of unresponsive tasks increased: 0 -> 2
```

**Comment by mihalycsaba** [comment]
```
[✓] Flutter (Channel stable, 3.24.4, on EndeavourOS 6.11.6-zen1-1.1-zen, locale en_US.UTF-8)
    • Flutter version 3.24.4 on channel stable at /nvme-data/Android/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (10 days ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /ssd2/csaba/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /ssd2/csaba/Android/Sdk
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8
    • cmake version 3.30.5
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2024.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • EndeavourOS 6.11.6-zen1-1.1-zen
    • Chrome (web)    • chrome • web-javascript • Google Chrome 130.0.6723.91

[✓] Network resources
    • All expected network resources are available.
```

**Comment by mihalycsaba** [comment]
Sorry I just followed the setup instructions from the site, I have totally forgot about the channels. Now I have modified the .fvmrc file to stable. fvm flutter --version prompted me to download the stable version.
For some reason flock defaults to impeller on stable too and has the same problem. I suspect, that's why my screen turns off and on and the emulator crashes. I don't get the impeller message with flutter.
